(* ::Package:: *)

BeginPackage["mypck`"]








TestManipulate::usage="funzione per gestione clustering"


Begin["Private`"]





imgD =Image[CompressedData["
1:eJztyjEKwkAQBdBFm1TBK3gL25S2EQ+QkDXYbGAjiFf0JrmFk1tYvAd/mPnM
eVz6xyGltDYx+uHd1Tp8bqc47mV9ziVP1/LKc66X8RhlG79bZN+/AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAB/7wcto292
"], "Byte", ColorSpace -> "RGB", ImageSize -> {Automatic, 63.54362416107383}, Interleaving -> True, MetaInformation -> Association["XMP" -> Association["XMPBasicSchema" -> Association["CreatorTool" -> "Adobe Photoshop CS6 (Macintosh)"], "XMPMediaManagementSchema" -> Association["InstanceID" -> "xmp.iid:E62194301E5D11E5941BFB3BD6212510", "DocumentID" -> "xmp.did:E62194311E5D11E5941BFB3BD6212510", "DerivedFrom" -> Association["Reference" -> Association["InstanceID" -> "xmp.iid:E621942E1E5D11E5941BFB3BD6212510", "DocumentID" -> "xmp.did:E621942F1E5D11E5941BFB3BD6212510"]]]], "Comments" -> Association["Software" -> "Adobe ImageReady"]]];
TestManipulate[]:=Manipulate[
If[Or[x =="KMeans",x =="KMedoids",x ==  "Spectral"],ClusteringComponents[ImageResize[imgD,200],cl,Method->x],ClusteringComponents[ImageResize[imgD,200],Method->x]]//Colorize,Row[{Item[FileNameSetter[Dynamic[selectedFile]],Alignment->Center],Button["Import",imgD=Import[selectedFile]]}], Control[{{x, "KMeans","Method"}, {"KMeans","KMedoids","Spectral","MeanShift","GaussianMixture","NeighborhoodContraction"}}],Control[{{cl, 1, "N. cluster"}, 1, 15, 1, Appearance -> "Labeled"}]];
(*TestManipulate[]:=Manipulate[ClusteringComponents[ImageResize[imgD,200],cl,Method\[Rule]x]//Colorize,Row[{Item[FileNameSetter[Dynamic[selectedFile]],Alignment->Center],Button["Import",imgD=Import[selectedFile]]}], Control[{{x, "KMeans","Method"}, {"KMeans","KMedoids","Spectral"}}], Control[{{cl, 1, "N. cluster"}, 1, 15, 1, Appearance -> "Labeled"}]];*)
(*TestManipulate[]:=Manipulate[ClusteringComponents[ImageResize[imgD,200],cl,Method\[Rule]x]//Colorize,Row[{Item[FileNameSetter[Dynamic[selectedFile]],Alignment->Center],Button["Import",imgD=Import[selectedFile]]}],{x,{"Agglomerate","KMedoids"}},Control[{{cl, 1, "n. cluster"}, 1, 15, 1, Appearance -> "Labeled"}]];*)
(*TestManipulate[img_]:=Manipulate[ClusteringComponents[img,Cl,Method->x]//Colorize,{x,{"Agglomerate","KMedoids"}},{Cl,1,20,1}];   Control[{{\:200ba, 1, "a"}, 0, 100000, 1, Appearance -> "Labeled"}
*)



End[]
